### ISSUE TITLE
上传历史中删除图片之后是所有图片重新加载了吗？

### ISSUE THREAD

**Issue by Yves0** [Aqours/Weibo-Picture-Store#29]

**Comment by Aqours** [comment]
√

**Comment by Yves0** [comment]
@Aqours 
是否可以部分刷新？这样体验会更好一点。现在每次删除图片之后会显示 Loading ，然后返回到列表顶部，如果要继续删除的话还得重新往下找图片。如果可以支持多选的话就更棒了

**Comment by Aqours** [comment]
这个上传记录本身的作用是查找以前的图片，更多的是展示，不会提供太多的交互操作。如果你想批量删除可以通过底部的微相册链接进入微相册进行批量操作，目前上传记录不会提供批量删除功能。

**Comment by Yves0** [comment]
好的，谢谢
