### ISSUE TITLE
希望加入 复制一篇文章到图床插件上，自动上传图片并替换地址

### ISSUE THREAD

**Issue by Seifon** [Aqours/Weibo-Picture-Store#32]
希望每次复制一篇文章，粘贴到图床上，可以自动将图片转换成微博图床的地址，然后显示转换好了图片的文章，这样就好了。

这样就不用看到一篇好文章，还要挨个下载图片再上传了。

**Comment by Aqours** [comment]
你要表达的意思是：已有的文章+其他网站的图片 => 粘贴 => 生成已有的文章+微博网站的图片

这个想法很赞同，但是 Weibo-Picture-Store(WPS) 扩展不会实现特定场景的功能。通过 [Tampermonkey](https://chrome.google.com/webstore/detail/dhdgffkkebhmkfjojejmpbldmpobfkfo) 扩展可以调用 WPS 的上传接口功能，你可以通过 Tampermonkey 扩展写脚本来实现你想要的特定功能。

**Comment by Seifon** [comment]
对的，就是这个意思。要是能实现就太好了。

另外从剪贴板粘贴图片的功能，然后转成外链的功能，貌似没有，希望也能加上。

**Comment by Seifon** [comment]
还有，我不太喜欢弹窗，希望插件能够增加网页形式的。

**Comment by Aqours** [comment]
@Seifon 
剪贴板粘贴图片的功能，这个功能是有的，仔细阅读文档。
网页形式可以访问 chrome-extension://pinjkilghdfhnkibhcangnpmcpdpmehk/popup.html 地址。
