### ISSUE TITLE
微博已登录，上传图片提示未登录

### ISSUE THREAD

**Issue by luojianxhlxt** [Aqours/Weibo-Picture-Store#33]
提示我登陆微博再试
可是我就是在微博界面尝试的。。。

**Comment by Aqours** [comment]
如果只是偶尔现象，应该是微博传图的接口挂掉了，一半过半天就好了。
其它情况请提供更多的信息以便排除错误（截图之类的）

**Comment by Aqours** [comment]
https://passport.weibo.com/visitor/visitor?entry=miniblog&a=enter&url=http%3A%2F%2Fweibo.com

访问上面的链接会丢失登陆

**Comment by Aqours** [comment]
可能的原因：
1. 新浪 https 和 http 的登陆认证 cookie 不一致
2. 浏览器发送请求的 cookie 被丢弃

目前没有确认，肯定的是登录上传失败是走到了访客系统导致的。参考：https://bindog.github.io/blog/2014/10/15/set-the-ua-to-bypass-sina-visitor-system/

**Comment by codexss** [comment]
HTTPS Everywhere 的问题，禁用解决 ;p

**Comment by Aqours** [comment]
@codexss 谢谢反馈

经测试是 HTTPS Everywhere 强制了 cookie 使用了 secure 导致 http 请求（图片上传只有 http 的接口）获取到的 cookie 不完整，即不能进行完整的身份校验，从而导致上传失败。而身份校验的接口 http 和 https 都可以用，因此会造成登录校验成功而上传失败的情况。

**Comment by codexss** [comment]
现在微博默认https了，http请求貌似有些问题了

**Comment by Aqours** [comment]
(⊙﹏⊙) 你这么说，我也不知道你说的什么问题呀

**Comment by Aqours** [comment]
@codexss (⊙﹏⊙) 你这么说，我也不知道你说的什么问题呀！有新问题可以另开 issue
