### ISSUE TITLE
Custom upload success callback

### ISSUE THREAD

**Issue by shuge** [Aqours/Weibo-Picture-Store#36]
如果想在上传成功后，将URL以POST请求发到指定服务器，应该再哪里添加好？

**Comment by Aqours** [comment]
暂时不能添加。

用户端暂时没法添加常驻脚本，只能针对特定的网页添加脚本。
如果你是针对某个页面，你的想法是可以实现的，但是这种方式对弹窗模式下上传的图片是无效的。不具有通用性，这个扩展也就没做支持。

**Comment by shuge** [comment]
明白，
谢谢。
