### ISSUE TITLE
身份信息校验成功，但是图片在某些情况下上传失败，疑似微博全站https的问题，将weibo.com及其子域名加入hsts后问题消失。

### ISSUE THREAD

**Issue by codexss** [Aqours/Weibo-Picture-Store#37]
![image](https://user-images.githubusercontent.com/5959201/32709215-aa1dd0ba-c869-11e7-8613-3c9252ff5e6d.png)
![image](https://user-images.githubusercontent.com/5959201/32709258-eccac76a-c869-11e7-9b53-2107a89ec974.png)

**Comment by Aqours** [comment]
301 后的 getStatus 请求返回的结果是什么？
正常流程在登录信息校验成功后，会再次触发 pic_upload.php 重试上传图片才对。

**Comment by codexss** [comment]
![image](https://user-images.githubusercontent.com/5959201/32709606-8ffd8ace-c86c-11e7-88ab-6fc2fdaac30c.png)

**Comment by codexss** [comment]
发送自 Windows 10 版邮件应用

发件人: L&H
发送时间: 2017年11月13日 12:13
收件人: Aqours/Weibo-Picture-Store
抄送: Lentin; Author
主题: Re: [Aqours/Weibo-Picture-Store]=?UTF-8?Q?_=E8=BA=AB=E4=BB=BD=E4=BF=A1=E6=81=AF=E6=A0=A1=E9=AA=8C=E6=88=90=E5=8A=9F=EF=BC=8C=E4=BD=86=E6=98=AF=E5=9B=BE=E7=89=87=E5=9C=A8=E6=9F=90=E4=BA=9B=E6=83=85=E5=86=B5=E4=B8=8B=E4=B8=8A=E4=BC=A0=E5=A4=B1=E8=B4=A5=EF=BC=8C=E7=96=91=E4=BC=BC=E5=BE=AE=E5=8D=9A=E5=85=A8=E7=AB=99https=E7=9A=84=E9=97=AE=E9=A2=98=EF=BC=8C=E5=B0=86weibo.com=E5=8F=8A=E5=85=B6=E5=AD=90=E5=9F=9F=E5=90=8D=E5=8A=A0=E5=85=A5hsts=E5=90=8E=E9=97=AE=E9=A2=98=E6=B6=88=E5=A4=B1=E3=80=82?==?UTF-8?Q?_=28#37=29?=

301 后的 getStatus 请求返回的结果是什么？
正常流程在登录信息校验成功后，会再次触发 pic_upload.php 重试上传图片才对。

**Comment by Aqours** [comment]
![2017-11-13_124245](https://user-images.githubusercontent.com/8586286/32710050-49e37360-c870-11e7-91c7-3d5fe31468b6.png)

你按照图示看一下 ③ 那个地方有么有打勾的。
PS: 你直接回邮件是都是乱码

**Comment by codexss** [comment]
![image](https://user-images.githubusercontent.com/5959201/32710206-5f1532fe-c871-11e7-9a33-b4ea51cb0249.png)

有对勾的

**Comment by Aqours** [comment]
分别试下下面两个方法：
1. 停用其它扩展，退出微博后再次登录，查看 cookie 是否还有 secure 打勾的（没有打勾的，第二个方法就不用试了）
2. 停用其它扩展，手动删除 secure 打勾的 cookie，登录微博，查看 cookie 是否还有 secure 打勾的

cookie 中没有 secure 打勾的，上图图片就不会出现所说的问题了。

**Comment by Aqours** [comment]
补充
具体原因参考：#33
