### ISSUE TITLE
影响ajax返回值！？

### ISSUE THREAD

**Issue by Lilaccoral** [Aqours/Weibo-Picture-Store#44]
虽然不是很确定，但从我机器排查的结果来看，这个插件影响了一般网页ajax返回内容了。。。。
![image](//wx1.sinaimg.cn/large/e0fcccbegy1fnkp94s7kdj211z06fwf2.jpg)
多了inject标签，会导致后面的解析代码报错。。。。

**Comment by Aqours** [comment]
重新发下图

**Comment by Lilaccoral** [comment]
http://wx4.sinaimg.cn/large/e0fcccbegy1fnkp94s7kdj211z06fwf2.jpg

**Comment by Aqours** [comment]
目前测试
```js
$.ajax({
    url: 'always-return-json',
    dataType: 'text/html',
})
```
这样的返回没有问题。
如果 $.ajaxFileUpload 的 dataType 和 jQuery 的用法是一样的话，你应该用 `html`，`text/html` 不是一个合法的值
