### ISSUE TITLE
网页放大 125% 的时候，上传页面无法完全展示所有内容

### ISSUE THREAD

**Issue by DemoJameson** [Aqours/Weibo-Picture-Store#45]
![image](https://user-images.githubusercontent.com/181192/35230867-32b43596-ffd2-11e7-93b3-215f82eabc7a.png)

**Comment by Aqours** [comment]
下面有滚动条可以拖动，或者把窗口拉大就可以了

**Comment by DemoJameson** [comment]
我是想能不能适配一下，不需要每次都去拖动滚动条。

**Comment by Aqours** [comment]
你是嫌字体太小了所以放大？
这个只能增大默认宽度来解决，但是放大到更大还是会出现滚动条。
不知道你是什么场景下需要放大来操作。

**Comment by DemoJameson** [comment]
因为我用的是 4K 34寸的屏幕，浏览器平时都是保持 125% 放大显示，所以打开这个窗口时会自动放大。

**Comment by Aqours** [comment]
你应该使用系统的缩放。
这样标题栏上的【微博图床】和下面的文字可以保持同等缩放比例。
浏览器缩放通常还是临时性的。

**Comment by DemoJameson** [comment]
系统使用了 150% 放大，是推荐值。不过浏览网页感觉还是偏小，所以我习惯再放大 125%。

**Comment by Aqours** [comment]
那默认宽度加大点。新版在 Chrome 65 上发布，近期不会更新。

https://chrome.google.com/webstore/detail/fgojeheijgbiibpekigaajhpendcghpi 这个是测试版，目前 Chrome Canary 版本才能用，测试版待会更新。

**Comment by DemoJameson** [comment]
thanks.

2018-01-24 16:19 GMT+08:00 L&H <notifications@github.com>:
